--1
CREATE DATABASE BooksCenter;
--2
USE[BooksCenter];
--3
CREATE TABLE[Users] (
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[Name] VARCHAR(255),
[Email] VARCHAR(255) NOT NULL,
[Password] VARCHAR(255) NOT NULL,
)
--4